---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: chatbot-test-app-15
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chatbot-test-app-15 
  name: chatbot-test-app-15
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi